"""update analysis_run

Revision ID: 2b514ba666a6
Revises: 8781f85f4f8c
Create Date: 2026-04-16 20:29:28.525116

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2b514ba666a6"
down_revision: Union[str, Sequence[str], None] = "8781f85f4f8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("analysis_runs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("pipeline_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("source_type", sa.String(), nullable=False))
        batch_op.create_foreign_key(
            "fk_analysis_runs_pipeline_id",
            "pipelines",
            ["pipeline_id"],
            ["pipeline_id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("analysis_runs", schema=None) as batch_op:
        batch_op.drop_constraint("fk_analysis_runs_pipeline_id", type_="foreignkey")
        batch_op.drop_column("source_type")
        batch_op.drop_column("pipeline_id")

    # ### end Alembic commands ###
