"""add last_opened_at columns

Revision ID: 3935e9811c6a
Revises: c96fb8759dbe
Create Date: 2026-04-24 16:26:34.258598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3935e9811c6a'
down_revision: Union[str, Sequence[str], None] = 'c96fb8759dbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_configurations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_opened_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_file_configurations_last_opened_at'), ['last_opened_at'], unique=False)

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_opened_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_files_last_opened_at'), ['last_opened_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_last_opened_at'))
        batch_op.drop_column('last_opened_at')

    with op.batch_alter_table('file_configurations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_configurations_last_opened_at'))
        batch_op.drop_column('last_opened_at')

    # ### end Alembic commands ###
