"""initialization database

Revision ID: 8781f85f4f8c
Revises: 
Create Date: 2026-04-16 18:05:37.283579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8781f85f4f8c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_methods',
    sa.Column('analysis_method_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('method_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('analysis_method_id'),
    sa.UniqueConstraint('method_name')
    )
    op.create_table('files',
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('sampling_rate', sa.Integer(), nullable=True),
    sa.Column('first_opened_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('file_id'),
    sa.UniqueConstraint('file_hash'),
    sa.UniqueConstraint('file_path')
    )
    op.create_table('preprocessing_methods',
    sa.Column('method_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('method_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('method_id'),
    sa.UniqueConstraint('method_name')
    )
    op.create_table('file_configurations',
    sa.Column('config_id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('configuration_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.file_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('config_id'),
    sa.UniqueConstraint('file_id', 'configuration_json', name='uix_file_config')
    )
    op.create_table('analysis_runs',
    sa.Column('analysis_run_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_id', sa.String(), nullable=False),
    sa.Column('analysis_method_id', sa.Integer(), nullable=True),
    sa.Column('parameters_json', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_method_id'], ['analysis_methods.analysis_method_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['config_id'], ['file_configurations.config_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_run_id')
    )
    op.create_table('pipelines',
    sa.Column('pipeline_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_id', sa.String(), nullable=True),
    sa.Column('pipeline_name', sa.String(), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('execution_time_seconds', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['file_configurations.config_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('pipeline_id')
    )
    op.create_table('visualization_plots',
    sa.Column('plot_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_id', sa.String(), nullable=False),
    sa.Column('plot_name', sa.String(), nullable=True),
    sa.Column('filters_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['file_configurations.config_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plot_id'),
    sa.UniqueConstraint('config_id', 'filters_json', name='uix_file_config')
    )
    op.create_table('analysis_results',
    sa.Column('result_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('result_path', sa.Text(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.analysis_run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_table('downloads',
    sa.Column('download_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=True),
    sa.Column('saved_path', sa.Text(), nullable=False),
    sa.Column('sampling_rate', sa.Integer(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.pipeline_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('download_id')
    )
    op.create_table('pipeline_steps',
    sa.Column('step_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('method_id', sa.Integer(), nullable=True),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('parameters_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['method_id'], ['preprocessing_methods.method_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.pipeline_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('step_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_steps')
    op.drop_table('downloads')
    op.drop_table('analysis_results')
    op.drop_table('visualization_plots')
    op.drop_table('pipelines')
    op.drop_table('analysis_runs')
    op.drop_table('file_configurations')
    op.drop_table('preprocessing_methods')
    op.drop_table('files')
    op.drop_table('analysis_methods')
    # ### end Alembic commands ###
