"""add signuture attribute

Revision ID: c96fb8759dbe
Revises: 2b514ba666a6
Create Date: 2026-04-22 15:24:17.006761

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c96fb8759dbe"
down_revision: Union[str, Sequence[str], None] = "2b514ba666a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # 1) Add signature as nullable first
    with op.batch_alter_table("pipelines", schema=None) as batch_op:
        batch_op.add_column(sa.Column("signature", sa.String(length=64), nullable=True))

    # 2) Fill old rows using pipeline_id
    op.execute(
        """
        UPDATE pipelines
        SET signature = 'legacy-' || pipeline_id
        WHERE signature IS NULL
    """
    )

    # 3) Make signature NOT NULL, then add index
    with op.batch_alter_table("pipelines", schema=None) as batch_op:
        batch_op.alter_column("signature", nullable=False)
        batch_op.create_index(
            batch_op.f("ix_pipelines_signature"), ["signature"], unique=False
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pipelines", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pipelines_signature"))
        batch_op.drop_column("signature")

    # ### end Alembic commands ###
