"""delete_downloads_table

Revision ID: e03b091989c8
Revises: 3935e9811c6a
Create Date: 2026-04-30 02:41:58.642200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e03b091989c8'
down_revision: Union[str, Sequence[str], None] = '3935e9811c6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('downloads')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downloads',
    sa.Column('download_id', sa.INTEGER(), nullable=False),
    sa.Column('pipeline_id', sa.INTEGER(), nullable=True),
    sa.Column('saved_path', sa.TEXT(), nullable=False),
    sa.Column('sampling_rate', sa.INTEGER(), nullable=True),
    sa.Column('downloaded_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.pipeline_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('download_id')
    )
    # ### end Alembic commands ###
